import { initializeApp } from "https://www.gstatic.com/firebasejs/9.22.1/firebase-app.js";
import { getFirestore, collection, addDoc, getDocs, doc, updateDoc, deleteDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/9.22.1/firebase-firestore.js";
import { getAuth, onAuthStateChanged, GoogleAuthProvider, signInWithPopup, signOut } from "https://www.gstatic.com/firebasejs/9.22.1/firebase-auth.js";

const firebaseConfig={apiKey:"AIzaSyDCwPw3WxwYHvaudHqYJ64RzhS4hWhKvO0",authDomain:"coco-healthcare-59401.firebaseapp.com",projectId:"coco-healthcare-59401",storageBucket:"coco-healthcare-59401.firebasestorage.app",messagingSenderId:"986920233821",appId:"1:986920233821:web:96ff08e9f118d557a816b4"};
const app=initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app);
let recordsRef=null;
let user=null,records=[],selectedPeriod='week',pain=0;
const $=id=>document.getElementById(id);
const today=()=>{const d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,10)};

$('recordDate').value=today();
$('loginButton').onclick=()=>signInWithPopup(auth,new GoogleAuthProvider()).catch(e=>alert('ログインできませんでした: '+e.message));
$('logoutButton').onclick=()=>user&&signOut(auth);
onAuthStateChanged(auth,async u=>{if(!u){user=null;recordsRef=null;$('authGate').hidden=false;$('appContent').hidden=true;$('savebar').hidden=true;return}user=u;recordsRef=collection(db,'users',user.uid,'personalHealthRecords');$('authGate').hidden=true;$('appContent').hidden=false;$('savebar').hidden=false;try{await loadRecords();loadDate($('recordDate').value)}catch(e){$('authGate').hidden=false;$('appContent').hidden=true;$('savebar').hidden=true;$('authMessage').textContent='このアカウントでは利用できません。';$('loginButton').textContent='別のアカウントでログイン'}});

document.querySelectorAll('.pain-btn').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.pain-btn').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');pain=Number(btn.textContent);$('painValue').textContent=pain});
document.querySelectorAll('.chips').forEach(group=>group.querySelectorAll('.chip').forEach(btn=>btn.onclick=()=>{if(group.classList.contains('single'))group.querySelectorAll('.chip').forEach(b=>b.classList.remove('on'));btn.classList.toggle('on')}));
document.querySelectorAll('.chart-tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.chart-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');selectedPeriod=btn.dataset.period;drawChart()});
$('recordDate').onchange=()=>loadDate($('recordDate').value);
$('saveButton').onclick=saveRecord;
$('deleteButton').onclick=deleteRecord;

async function loadRecords(){const snap=await getDocs(recordsRef);records=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>a.date.localeCompare(b.date));drawChart()}
function activeOne(id){return $(id).querySelector('.chip.on')?.dataset.value||'なし'}
function activeMany(id){return [...$(id).querySelectorAll('.chip.on')].map(b=>b.dataset.value)}
function setOne(id,value){$(id).querySelectorAll('.chip').forEach(b=>b.classList.toggle('on',b.dataset.value===(value||'なし')))}
function setMany(id,values=[]){$(id).querySelectorAll('.chip').forEach(b=>b.classList.toggle('on',values.includes(b.dataset.value)))}
function setPain(value){pain=Number(value)||0;document.querySelectorAll('.pain-btn').forEach(b=>b.classList.toggle('selected',Number(b.textContent)===pain));$('painValue').textContent=pain}
function loadDate(date){const r=records.find(x=>x.date===date);setPain(r?.painScore||0);$('painComment').value=r?.painComment||'';setOne('periodStatus',r?.periodStatus);$('periodComment').value=r?.periodComment||'';setOne('headacheStatus',r?.headacheStatus);$('headacheComment').value=r?.headacheComment||'';setMany('otherSymptoms',r?.otherSymptoms);$('symptomComment').value=r?.symptomComment||'';$('dailyMemo').value=r?.memo||'';$('saveButton').textContent=r?'この日の記録を更新':'今日の記録を保存';$('deleteButton').style.display=r?'block':'none';$('saveStatus').textContent=r?'保存済みの記録を表示しています':''}
async function saveRecord(){const date=$('recordDate').value;if(!date)return;const existing=records.find(r=>r.date===date),data={date,painScore:pain,painComment:$('painComment').value.trim(),periodStatus:activeOne('periodStatus'),periodComment:$('periodComment').value.trim(),headacheStatus:activeOne('headacheStatus'),headacheComment:$('headacheComment').value.trim(),otherSymptoms:activeMany('otherSymptoms'),symptomComment:$('symptomComment').value.trim(),memo:$('dailyMemo').value.trim(),updatedAt:serverTimestamp()};$('saveButton').disabled=true;$('saveStatus').textContent='保存中…';try{existing?await updateDoc(doc(recordsRef,existing.id),data):await addDoc(recordsRef,{...data,createdAt:serverTimestamp()});await loadRecords();loadDate(date);$('saveStatus').textContent='保存しました'}catch(e){$('saveStatus').textContent='保存できませんでした';alert('保存できませんでした: '+e.message)}finally{$('saveButton').disabled=false}}
async function deleteRecord(){const r=records.find(x=>x.date===$('recordDate').value);if(!r||!confirm('この日の記録を削除しますか？'))return;await deleteDoc(doc(recordsRef,r.id));await loadRecords();loadDate($('recordDate').value);$('saveStatus').textContent='削除しました'}

function average(vals){const v=vals.filter(Number.isFinite);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}
function chartModel(){const end=new Date($('recordDate').value+'T00:00:00');if(selectedPeriod==='week'){const items=[];for(let i=6;i>=0;i--){const d=new Date(end);d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10),r=records.find(x=>x.date===key);items.push({label:i===0?'今日':String(d.getDate()),value:r?.painScore??null})}return{title:'最近7日間の痛みの推移',series:[{name:'痛み',color:'#d65f78',items}]}}if(selectedPeriod==='month'){const y=end.getFullYear(),m=end.getMonth(),days=new Date(y,m+1,0).getDate(),items=[];for(let day=1;day<=days;day++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,r=records.find(x=>x.date===key);items.push({label:[1,8,15,22,days].includes(day)?String(day):'',value:r?.painScore??null})}return{title:`${y}年${m+1}月の日ごとの痛み`,series:[{name:'痛み',color:'#d65f78',items}]}}const years=[...new Set(records.map(r=>Number(r.date.slice(0,4))))].sort();if(!years.includes(end.getFullYear()))years.push(end.getFullYear());const palette=['#d65f78','#7569b6','#4d8b78','#d6924a','#4f7fb5'];return{title:'1月〜12月・年ごとの平均痛み',series:years.sort().map((year,i)=>({name:`${year}年`,color:palette[i%palette.length],items:Array.from({length:12},(_,m)=>({label:`${m+1}月`,value:average(records.filter(r=>r.date.startsWith(`${year}-${String(m+1).padStart(2,'0')}`)).map(r=>r.painScore))}))}))}}
function drawChart(){const model=chartModel(),svgW=545,left=35;$('chartTitle').textContent=model.title;$('chartCompare').textContent=records.length?`${records.length}日分の記録`:'まだ記録がありません';const count=model.series[0].items.length,step=count>1?svgW/(count-1):0;$('chartArea').setAttribute('d','');$('chartLine').setAttribute('points','');$('compareLine').setAttribute('points','');$('chartDots').innerHTML='';const extra=[...document.querySelectorAll('.dynamic-series')];extra.forEach(e=>e.remove());model.series.forEach((s,si)=>{const points=s.items.map((item,i)=>item.value===null?null:`${left+i*step},${135-item.value*11}`).filter(Boolean).join(' '),line=document.createElementNS('http://www.w3.org/2000/svg','polyline');line.setAttribute('class','dynamic-series');line.setAttribute('points',points);line.setAttribute('fill','none');line.setAttribute('stroke',s.color);line.setAttribute('stroke-width','3');line.setAttribute('stroke-linecap','round');line.setAttribute('stroke-linejoin','round');$('chartDots').before(line);s.items.forEach((item,i)=>{if(item.value===null)return;const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('class','dot dynamic-series');c.setAttribute('cx',left+i*step);c.setAttribute('cy',135-item.value*11);c.setAttribute('r','3');c.setAttribute('style',`stroke:${s.color}`);$('chartDots').before(c)})});$('chartLabels').innerHTML=model.series[0].items.map((item,i)=>`<text x="${left+i*step}" y="158" font-size="${selectedPeriod==='year'?8:10}">${item.label}</text>`).join('');$('chartLegend').innerHTML=model.series.map(s=>`<span><i class="legend-dot" style="background:${s.color}"></i>${s.name}</span>`).join('');$('chartLegend').classList.toggle('show',selectedPeriod==='year')}
